dist: trusty
sudo: required 
language: cpp

services:
  - docker


# Add debian back to environment after this bug is resolved:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=896644
# Severity: serious
#
#    - os: linux
#      env: IMAGE=debian:sid

matrix:
  include:
    - os: linux
      env: IMAGE=fedora:27
    - os: linux
      env: IMAGE=fedora:26
    - os: linux
      env: IMAGE=debian:buster
    - os: linux
      env: IMAGE=ubuntu:artful
    - os: linux
      env: IMAGE=ubuntu:bionic


script: travis_retry ci/one.sh
