---

- name: install ppas for debian compiler and emacs
  apt_repository: repo='{{item}}' state=present
  sudo: yes
  with_items:
    - 'ppa:ubuntu-toolchain-r/test'
    - 'ppa:ubuntu-elisp/ppa'

- name: Install all dev system tools
  sudo: yes
  apt:
    name='{{item}}'
    state=installed
    update_cache=yes
    cache_valid_time=3600
    force=yes
  with_items:
    - 'g++-5'
    - 'gcc-5'
    - 'g++-5-multilib'
    - 'gcc-5-multilib'
    - 'gcc-5-doc'
    - 'ccache'
    - 'cmake'
    - 'git'
    - 'binutils-gold'
    - 'ccache'
    - 'clang-3.6'
    - 'clang-format-3.6' # compiler needed
    - 'clang-modernize-3.6' # compiler formatter
    - 'libgoogle-perftools-dev' # profiling tools
    - 'doxygen' # needed for docs
