---
- name: install deps
  become: yes
  dnf:
    name='{{item}}'
  with_items:
    - libaio-devel
    - ninja-build
    - ragel
    - hwloc-devel
    - numactl-devel
    - libpciaccess-devel
    - cryptopp-devel
    - xen-devel
    - boost-devel
    - libxml2-devel
    - xfsprogs-devel
    - gnutls-devel
    - libubsan
    - libasan
    - lksctp-tools-devel
    - lz4-devel
    - protobuf-devel
    - protobuf-compiler
    - libunwind-devel
    - systemtap-sdt-devel


- name: programs for posix ethernet tunning and IRQ balance
  become: yes
  dnf:
    name='{{item}}'
  with_items:
    - hwloc


- name: Sync soure from git
  git:
    repo='https://github.com/scylladb/seastar.git'
    accept_hostkey=yes
    clone=yes
    dest='{{goobly_cache_dir}}/seastar'
    update=yes
    recursive=yes
    force=yes
    version='243f45e'

- name: configure sources with dpdk enabled
  command: ./configure.py --enable-dpdk
  args:
    chdir: '{{goobly_cache_dir}}/seastar'
    creates: '{{goobly_cache_dir}}/seastar/build.ninja'

- name: build with ninja
  shell: "ninja-build -j$((({{ansible_processor_vcpus}}-1)))"
  args:
    chdir: '{{goobly_cache_dir}}/seastar'
    creates: '{{goobly_cache_dir}}/seastar/build/release/libseastar.a'
